export const S = {
  card: {
    background: "#132013",
    border: "1px solid #1e3a1e",
    borderRadius: 14,
    padding: "16px 18px",
    marginBottom: 12,
  },
  label: {
    fontSize: 10,
    letterSpacing: 3,
    color: "#4ade80",
    textTransform: "uppercase",
    marginBottom: 10,
    display: "block",
  },
  input: {
    width: "100%",
    background: "#0f2010",
    border: "1px solid #1e3a1e",
    borderRadius: 8,
    padding: "11px 13px",
    color: "#d4e6c3",
    fontSize: 14,
    marginBottom: 10,
    fontFamily: "inherit",
    outline: "none",
    WebkitAppearance: "none",
    boxSizing: "border-box",
  },
  btn: {
    background: "#1a4a1a",
    border: "1px solid #2a6a2a",
    color: "#4ade80",
    padding: "10px 18px",
    borderRadius: 22,
    fontSize: 12,
    cursor: "pointer",
    fontFamily: "inherit",
    letterSpacing: 1,
    WebkitAppearance: "none",
  },
  tag: (signal, colors) => ({
    fontSize: 10,
    padding: "3px 10px",
    borderRadius: 20,
    background: `${colors[signal]}22`,
    color: colors[signal],
    whiteSpace: "nowrap",
    letterSpacing: 0.5,
    flexShrink: 0,
  }),
  sectionTitle: {
    fontSize: 10,
    letterSpacing: 3,
    color: "#4ade80",
    textTransform: "uppercase",
    marginBottom: 14,
    display: "block",
  },
  muted: { fontSize: 12, color: "#6b9e6b" },
  body: { fontSize: 13, color: "#94a3b8", lineHeight: 1.6 },
  display: { fontFamily: "'Playfair Display', serif", color: "#e8f5e0" },
};
